# Generated by Django 5.0.7 on 2025-09-12 17:32

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expiration_time',
            field=models.DateTimeField(db_index=True, default=base.models.default_expiration_time, editable=False),
        ),
    ]
